card_bg_sizepx:
  type: string
  default: 30px
  description:
    en: ""

card_flair_sizepx:
  type: string
  default: 30px
  description:
    en: ""

post_flair_bg_sizepx:
  type: string
  default: 30px
  description:
    en: ""

post_flair_sizepx:
  type: string
  default: 30px
  description:
    en: ""

  type: string
  default: 30px
  description:
    en: ""

flair_groups:
  type: list
  list_type: group
  default: ""
  description:
    en: "Use custom flair for these groups only."
