card_bg_sizepx:
  type: string
  default: 30px
  description:
    en: ""

card_flair_sizepx:
  type: string
  default: 30px
  description:
    en: ""

post_flair_bg_sizepx:
  type: string
  default: 30px
  description:
    en: ""

post_flair_sizepx:
  type: string
  default: 30px
  description:
    en: ""

  type: string
  default: 30px
  description:
    en: ""
